import {
	bridal,
	commercial,
	editorial,
	specialOccasions,
} from "../components/ImgTag";

const images = [
	{
		id: "0",
		title: "Bridal",
		src: `${bridal["bridal1.jpg"].default}`,
		alt: "bridal",
		category: "Bridal",
	},
	{
		id: "1",
		title: "Bridal",
		src: `${bridal["bridal2.jpg"].default}`,
		alt: "bridal",
		category: "Bridal",
	},
	{
		id: "2",
		title: "Bridal",
		src: `${bridal["bridal3.jpg"].default}`,
		alt: "bridal",
		category: "Bridal",
	},
	{
		id: "3",
		title: "Bridal",
		src: `${bridal["bridal4.jpg"].default}`,
		alt: "bridal",
		category: "Bridal",
	},
	{
		id: "4",
		title: "Bridal",
		src: `${bridal["bridal5.jpg"].default}`,
		alt: "bridal",
		category: "Bridal",
	},
	{
		id: "5",
		title: "Bridal",
		src: `${bridal["bridal6.jpg"].default}`,
		alt: "bridal",
		category: "Bridal",
	},
	{
		id: "6",
		title: "Beauty/Editorial",
		src: `${editorial["editorial1.jpg"].default}`,
		alt: "beauty and editorial",
		category: "Beauty and Editorial",
	},
	{
		id: "7",
		title: "Beauty/Editorial",
		src: `${editorial["editorial2.jpg"].default}`,
		alt: "beauty and editorial",
		category: "Beauty and Editorial",
	},
	{
		id: "8",
		title: "Occasions",
		src: `${specialOccasions["image3.jpg"].default}`,
		alt: "occasions",
		category: "Occasions",
	},
	{
		id: "9",
		title: "Occasions",
		src: `${specialOccasions["image2.jpg"].default}`,
		alt: "occasions",
		category: "Occasions",
	},
	{
		id: "10",
		title: "Commercial",
		src: `${commercial["commercial1.jpg"].default}`,
		alt: "commercial",
		category: "Commercial",
	},
	{
		id: "11",
		title: "Commercial",
		src: `${commercial["commercial2.jpg"].default}`,
		alt: "commercial",
		category: "Commercial",
	},
	{
		id: "13",
		title: "Bridal",
		src: `${bridal["bridal7.jpg"].default}`,
		alt: "bridal",
		category: "Bridal",
	},
	{
		id: "14",
		title: "Beauty/Editorial",
		src: `${editorial["editorial3.jpg"].default}`,
		alt: "beauty and editorial",
		category: "Beauty and Editorial",
	},
	{
		id: "15",
		title: "Beauty/Editorial",
		src: `${editorial["editorial4.jpg"].default}`,
		alt: "beauty and editorial",
		category: "Beauty and Editorial",
	},
	{
		id: "16",
		title: "Beauty/Editorial",
		src: `${editorial["editorial5.jpg"].default}`,
		alt: "beauty and editorial",
		category: "Beauty and Editorial",
	},
	{
		id: "17",
		title: "Beauty/Editorial",
		src: `${editorial["editorial6.jpg"].default}`,
		alt: "beauty and editorial",
		category: "Beauty and Editorial",
	},
	{
		id: "18",
		title: "Beauty/Editorial",
		src: `${editorial["editorial7.jpg"].default}`,
		alt: "beauty and editorial",
		category: "Beauty and Editorial",
	},
	{
		id: "19",
		title: "Beauty/Editorial",
		src: `${editorial["editorial8.jpg"].default}`,
		alt: "beauty and editorial",
		category: "Beauty and Editorial",
	},
	{
		id: "20",
		title: "Beauty/Editorial",
		src: `${editorial["editorial9.jpg"].default}`,
		alt: "beauty and editorial",
		category: "Beauty and Editorial",
	},
	{
		id: "21",
		title: "Occasions",
		src: `${specialOccasions["image1.jpg"].default}`,
		alt: "special occasions",
		category: "Occasions",
	},
	{
		id: "22",
		title: "Occasions",
		src: `${specialOccasions["image4.jpg"].default}`,
		alt: "occasions",
		category: "Occasions",
	},
	{
		id: "23",
		title: "Occasions",
		src: `${specialOccasions["image5.jpg"].default}`,
		alt: "occasions",
		category: "Occasions",
	},
];

export default images;
