const images = [
  {
    id: "0",
    title: "Bridal",
    src: "http://localhost:5000/uploads/bridal/bridal1.jpg",
    alt: "bridal",
    category: "Bridal",
  },
  {
    id: "1",
    title: "Bridal",
    src: "http://localhost:5000/uploads/bridal/bridal2.jpg",
    alt: "bridal",
    category: "Bridal",
  },
  {
    id: "2",
    title: "Bridal",
    src: "http://localhost:5000/uploads/bridal/bridal3.jpg",
    alt: "bridal",
    category: "Bridal",
  },
  {
    id: "3",
    title: "Bridal",
    src: "http://localhost:5000/uploads/bridal/AmberMariePhotography-4.jpg",
    alt: "bridal",
    category: "Bridal",
  },
  {
    id: "4",
    title: "Bridal",
    src: "http://localhost:5000/uploads/bridal/AmberMariePhotography-58.jpg",
    alt: "bridal",
    category: "Bridal",
  },
  {
    id: "5",
    title: "Bridal",
    src: "http://localhost:5000/uploads/bridal/AmberMariePhotography-63.jpg",
    alt: "bridal",
    category: "Bridal",
  },
  {
    id: "6",
    title: "Beauty/Editorial",
    src: "https://via.placeholder.com/600x353.png",
    alt: "beauty and editorial",
    category: "Beauty and Editorial",
  },
  {
    id: "7",
    title: "Beauty/Editorial",
    src: "https://via.placeholder.com/600x354.png",
    alt: "beauty and editorial",
    category: "Beauty and Editorial",
  },
  {
    id: "8",
    title: "Occasions",
    src: "https://via.placeholder.com/600x355.png",
    alt: "occasions",
    category: "Occasions",
  },
  {
    id: "9",
    title: "Occasions",
    src: "https://via.placeholder.com/600x356.png",
    alt: "occasions",
    category: "Occasions",
  },
  {
    id: "10",
    title: "Commercial",
    src: "http://localhost:5000/uploads/commercial/image1.jpg",
    alt: "commercial",
    category: "Commercial",
  },
  {
    id: "11",
    title: "Commercial",
    src: "http://localhost:5000/uploads/commercial/image2.jpg",
    alt: "commercial",
    category: "Commercial",
  },
  {
    id: "12",
    title: "Commercial",
    src: "http://localhost:5000/uploads/commercial/Kaiser-by-Felix-Groteloh - Copy.jpg",
    alt: "commercial",
    category: "Commercial",
  },
];

export default images;
